### ISSUE TITLE
How to display png image in Android?

### ISSUE THREAD

**Issue by kylin17** [julienr/libpng-android#13]
Is that any example to show usage?

**Comment by julienr** [comment]
Unfortunately no, there is no usage example. The thing is displaying an image (or really anything) from a native app on Android is quite complicated.

You either have to go through Java (using JNI) like in this example https://github.com/tsaarni/android-native-egl-example

or you can do it fully native like in this example 
https://github.com/googlesamples/android-ndk/tree/master/gles3jni

In both case, this involves quite a bit of OpenGL. So if you just want to display a PNG, doing it 100% in Java (using an ImageView) is a much simpler solution.
