### ISSUE TITLE
undefined reference to `png_create_write_struct'

### ISSUE THREAD

**Issue by ebortolini** [julienr/libpng-android#2]
Hi,
I am trying to use this library. A generated a static library and included in my project. I included png.h in my source file and compiled with : LOCAL_STATIC_LIBRARIES := libpng

But it cannot compile, and show undefined reference to `png_create_write_struct'. Looks that it isn't found references.

**Comment by julienr** [comment]
That's strange. Are you importing the libpng with something like :

```
$(call import-module, libpng-android/jni) 
```

The libpng-android folder must be in your NDK_MODULE_PATH environment variable.

If that doesn't work, can you post your Android.mk, the command you use to compile and full compilation output (in a gist and link it here) ?

**Comment by ebortolini** [comment]
Hi,

I am using this library as a static library. When I was compiling my code, was missing the : LOCAL_SHARED_LIBRARIES := -lz

After I added this line, all worked fine.

Thank you.
