### ISSUE TITLE
Needs update to version 1.6.20

### ISSUE THREAD

**Issue by ip** [julienr/libpng-android#4]

**Comment by julienr** [comment]
I will not have time to work on this in the near future,but I'd be happy to
accept pull requests.

**Comment by ip** [comment]
I switched to [LodePNG](https://github.com/lvandeve/lodepng) (maybe it would be helpful to you)

**Comment by julienr** [comment]
LodePNG looks interesting, I added a link in the README. Thanks

**Comment by julienr** [comment]
This was fixed by #5
