### ISSUE TITLE
arm64-v8a build fail with missing neon intrinsics

### ISSUE THREAD

**Issue by netx123** [julienr/libpng-android#6]
Hi, your distribution is missing the libpng arm directory, so when building for arm64-v8a architectures which support NEON, the build fails with 'undefined reference to 'png_init_filter_functions_neon'

**Comment by sreejith-mohanan** [comment]
Changing the line number 130 in pngpriv.h form 

# define PNG_ARM_NEON_OPT 2

to 

# define PNG_ARM_NEON_OPT 0

will avoid neon optimization in arm and will fix the bug

**Comment by mlknz** [comment]
Fix worked for me.

**Edit:**
@julienr could you repair distribution please? Adding arm directory to sources and Android.mk solves issue.

**Edit 2:**
I have created PR which fixes the issue for me.
https://github.com/julienr/libpng-android/pull/11

**Comment by julienr** [comment]
@mlknz Merged the PR, thanks !
