### ISSUE TITLE
Is there any way to change CMYK to RGB color space of image using your library..?

### ISSUE THREAD

**Issue by ddpatel2606** [julienr/libpng-android#7]
Is there any way to change CMYK to RGB color space of image using your library..?

**Comment by julienr** [comment]
To my knowledge, the PNG format only supports the RGB colorspace, so I believe the answer is no. Note that this repo is just a repackaging of libpng for Android, the official libpng repository is [here](https://github.com/glennrp/libpng).

 [This thread](http://stackoverflow.com/questions/12074315/convert-image-byte-from-cmyk-to-rgb) seems to have some pointers on how to do colorspace conversion on Android (haven't tested them).
