### ISSUE TITLE
issue with libpng 1.5 and later

### ISSUE THREAD

**Issue by laitr01** [julienr/libpng-android#8]
libpng-1.5 and later do not allow direct access to the members of png_ptr, i replaced new version in my project and it went wrong. can you give idea to build libpng version 1.2.56

**Comment by netx123** [comment]
Depends which members you're talking about?
I believe that most restricted member variables can now be accessed by the equivalent public "get" method, for example
`png_ptr->jmpbuf`
Becomes:
`png_jmpbuf(png_ptr)`
